<a href="https://colab.research.google.com/github/emilsar/Cedars/blob/main/Numpy_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1D Tensors

In [7]:
import numpy as np

#1D (vector)
v=np.array([2,3,5])
print(v)
print("Shape:",v.shape)
print("Dimension:",v.ndim)
print(v*2)
print(v+2)
print("Sum:",np.sum(v))
print("Mean:",np.mean(v))

[2 3 5]
Shape: (3,)
Dimension: 1
[ 4  6 10]
[4 5 7]
Sum: 10
Mean: 3.3333333333333335


# 2D Tensors: Matrices


In [28]:
#2D Arrays
M=np.array([ [2,3,5] ,[7,9,11]  ])
A=np.array([[1,2],[3,5]])
B=np.array([[2,3],[5,6]])
#print(M)
#print("Shape:",M.shape)
#print("Dimension:",M.ndim)

#Access
#The row does not matter, pick column 2
M[:,2]
#The column does not matte, pick row 1
M[0,:]
#sum up the first column
#Each axis corresponds to a dimension of movement through the array.
#Axis 0 → moves down the rows (changes the row index)
#Axis 1 → moves across the columns (changes the column index)
print(np.sum(M[:,0]))
#Sum by column:
print(np.sum(M,axis=0))
print(M.T) #Matrix Transpose
print(np.matmul(A,B))

9
[ 9 12 16]
[[ 2  7]
 [ 3  9]
 [ 5 11]]
[[12 15]
 [31 39]]


# 3D Tensors: Matrixes