<a href="https://colab.research.google.com/github/emilsar/Cedars/blob/main/Numpy_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1D Tensors

In [ ]:
import numpy as np

#1D (vector)
v=np.array([2,3,5])
print(v)
print("Shape:",v.shape)
print("Dimension:",v.ndim)
print(v*2)
print(v+2)
print("Sum:",np.sum(v))
print("Mean:",np.mean(v))

[2 3 5]
Shape: (3,)
Dimension: 1
[ 4  6 10]
[4 5 7]
Sum: 10
Mean: 3.3333333333333335


# 2D Tensors: Matrices


In [ ]:
#2D Arrays
M=np.array([ [2,3,5] ,[7,9,11]  ])
A=np.array([[1,2],[3,5]])
B=np.array([[2,3],[5,6]])
#print(M)
#print("Shape:",M.shape)
#print("Dimension:",M.ndim)

#Access
#The row does not matter, pick column 2
M[:,2]
#The column does not matte, pick row 1
M[0,:]
#sum up the first column
#Each axis corresponds to a dimension of movement through the array.
#Axis 0 → moves down the rows (changes the row index)
#Axis 1 → moves across the columns (changes the column index)
print(np.sum(M[:,0]))
#Sum by column:
print(np.sum(M,axis=0))
print(M.T) #Matrix Transpose
print(np.matmul(A,B))

9
[ 9 12 16]
[[ 2  7]
 [ 3  9]
 [ 5 11]]
[[12 15]
 [31 39]]


# 3D Tensors: Matrixes

# Urothelian Images

In [1]:
!git clone https://github.com/emilsar/Cedars.git
%cd Cedars/Project3/imagedata/X

Cloning into 'Cedars'...
remote: Enumerating objects: 1121, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 1121 (delta 15), reused 4 (delta 0), pack-reused 1088 (from 2)
Receiving objects: 100% (1121/1121), 1.22 GiB | 20.86 MiB/s, done.
Resolving deltas: 100% (392/392), done.
Updating files: 100% (891/891), done.
/content/Cedars/Project3/imagedata/X


In [2]:
%ls-al

0.npy    120.npy  141.npy  162.npy  183.npy  23.npy  44.npy  65.npy  86.npy
100.npy  121.npy  142.npy  163.npy  184.npy  24.npy  45.npy  66.npy  87.npy
101.npy  122.npy  143.npy  164.npy  185.npy  25.npy  46.npy  67.npy  88.npy
102.npy  123.npy  144.npy  165.npy  186.npy  26.npy  47.npy  68.npy  89.npy
103.npy  124.npy  145.npy  166.npy  187.npy  27.npy  48.npy  69.npy  8.npy
104.npy  125.npy  146.npy  167.npy  188.npy  28.npy  49.npy  6.npy   90.npy
105.npy  126.npy  147.npy  168.npy  189.npy  29.npy  4.npy   70.npy  91.npy
106.npy  127.npy  148.npy  169.npy  18.npy   2.npy   50.npy  71.npy  92.npy
107.npy  128.npy  149.npy  16.npy   190.npy  30.npy  51.npy  72.npy  93.npy
108.npy  129.npy  14.npy   170.npy  191.npy  31.npy  52.npy  73.npy  94.npy
109.npy  12.npy   150.npy  171.npy  192.npy  32.npy  53.npy  74.npy  95.npy
10.npy   130.npy  151.npy  172.npy  193.npy  33.npy  54.npy  75.npy  96.npy
110.npy  131.npy  152.npy  173.npy  194.npy  34.npy  55.npy  76.npy  97.npy
111.npy  132.